### ISSUE TITLE
Project requirements checklist

### ISSUE THREAD

**Issue by banunkers** [MTBorg/M7011E_lab#118]
### Advanced
- [ ] Electricity consumption is to some extent (in Luleå highly) dependent on weather since heating a house consumes a lot of energy. Your simulator could include this by simulating outdoor temperature or even connect to open API’s on the web in order to ask for the current temperature (Note that wind speed should be modelled “by hand” for educational purposes, and should not be taken from such an API)
- [x] Model downtime or breakdowns of the wind turbines
- [ ] Have your simulator include locational data such as GPS coordinates in order to make  the wind speed in two locations in proximity to each other have similar wind speeds
- [ ] Your simulator could provide historical data
- [ ] The simulator could, in extension to the REST API, provide streaming simulation data over a socket or similar

### Basic
- [x] Sign up, login, and logout (make sure to apply proper security principles).
- [x] See the following (as text): 
  - the current wind
  - current production
  - current consumption
  - net production (i.e. the current production minus the current consumption)
  - how much is in the buffer
  - current electricity price on the market
- [x] In case of excessive production, Prosumer should be able to control the ratio of how much should be sold to the market and how much should be sent to the buffer.
- [x] In case of under-production, control the ratio of how much should be bought from the market and how much should be taken from the buffer.
- [x] The Prosumer can read values from the simulator, and values should be sampled at a rate of 0.1 Hz or higher.
- [x] Should be able to upload a picture of the Prosumer’s house (that is then visible in the application).

### Advanced
- [ ] The monitoring panel can be made more user-friendly by for example including gauges for displaying:
  - Consumption
  - Wind speed
- [x] Sliders or other suitable controls for determining the ratio from/to the market and buffer
- [ ] A chat where messages from system administrators or friends can be displayed
- [ ] The monitoring system should be responsive (e.g. have a mobile view)
- [ ] The monitoring system should handle multiple logins (e.g. one from mobile, one from desktop)
- [x] There should be a profile page where the Prosumer can update credentials and delete his/her account
- [ ] Messages in the chat has a priority and filters for low, medium, high. High priority messages issues a special notification to the user (e.g. a sound, pop-up etc). 
- [ ] The messages in the chat must not suffer from XSS vulnerabilities etc.
- [ ] The Prosumer can re-order the visual gauges for example using drag-n-drop
- [ ] The data stream from the simulator is made “real time” i.e. streaming from the simulator
- [ ] The Prosumer can add “Warning level thresholds” that issues notifications when for example the Battery buffer drops below a certain value
- [ ] Have a “friends” list of other Prosumer’s which they are allowed to interact with (e.g. see their information etc)
- [ ] Push-to-talk button for contacting the Manager or friends over voice
- [ ] Analyze QoS for response times etc. Issue warnings if the server responds slowly or even implement dead reckoning or similar to cope with server downtimes

### Basic
- [x] Through a profile page update credentials and delete the users account (not the manager).  A picture of the Manager must be uploaded and shown in the profile
- [ ] See and control the Coal Power plant’s electricity production
- [ ] See the Coal Power plant’s status: starting, running, stopped
- [ ] When producing, control a ratio of electricity being sent to the buffer and to the market (when stopped the buffer should be used to supply the market demand)
- [ ] See the current Market demand
- [ ] Should a black-out occur in the system (failing to provide one or more houses with electricity) the Manager should see which Prosumers that are affected
- [ ] See the modelled electricity price (obtained from the Simulator and used as a guidance by the Manager when setting the current electricity price)
- [ ] See and set the current electricity price
- [ ] Have a list of a Prosumers from which the Manager can:
  - Be able to see who is online (logged in)
  - Be able to view this Prosumer’s system
  - Block the Prosumer from selling to the market for (10-100 seconds)

### Advanced
- [ ] Add IP and port to the list of Prosumers (and other interesting/useful information e.g. last login)
- [ ] User interface is not “polling” over REST, but instead streams data over e.g. a socket
- [ ] Monitoring and displaying network delays in the system
- [ ] Introduce different useful alarms 
- [ ] Make a bot that can replace the Manager - Monitors values, redirects to buffer or market,sends messages to users etc.
- [ ] Should be able to use from multiple devices e.g. desktop and mobile (responsive)
- [ ] Should be able to use simultaneously from multiple devices
- [ ] An “notification” field or chat where messages from a Prosumer can be received
- [ ] There is a visual representation (e.g. Gauges) of the different values and graphical tools (e.g. sliders etc) for controlling the plant
- [ ] Messages from Providers can be given a priority and one could add filters for low, medium, high. Also each message has an acknowledge button. The messages must not suffer from XSS vulnerabilities etc.
- [ ] The operator can re-order the visual gauges for example using drag-n-drop
- [ ] Push-to-talk button for contacting a Prosumer over voice, or even a video function
- [ ] Perform dead reckoning of the system to save data traffic (e.g. broadcast operator commands/data to all connected to the plant and then dead reckon the state of the system. Eventual corrections with real data is needed).
